- hosts: localhost

  vars:
    s_k2: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDG/IgMrNfksndGMn/QIjVOIbga/Cr3qQ1v2HRtJi/a4BY0x6bh
        eAMuT6TIwOs2McM4qfAiZDKbgBYUhMttT1kqw5YUTPktScs6wGXYpjTNkQx3w8Ob
        FT1e8ScnsMYW6gpB4WOrZAYiby1+cb13cRThCJ9YB3a52shQqbAGS647CQIBIwKB
        gQC7naTYwDlFV8+LVC9d1xxQ+ziOeLrMQE5/Za+aHLDHDcvLXShQ7X9XjOvTOY1Q
        Ws4COdPIp51uCw2BD335WXFSiVteryrNzKyLZJHkIBDVgoiwMUcqLolokxkJ1dzQ
        W5WfiA48PvqC/wZPh1ZNWrKcXxniuuJ2mzhQlYd3EnVIZwJBAPde5o3xSxi48JI+
        B6SWs9Dqfxzd/iQW47ghc8giTKNECVTxteQrjoO2Y9nUmaSaNqd2atsmOmjKZGgf
        rgkBeucCQQDN7YtDTtlfwCLyCTRjfLst7hb+RM1LbfUJnZI0XICvVhM6NFDA7+n0
        Qd2EfdGTEpAq1ys/UMtZAEF0bUaT8kyPAkEAhkl12AalHAyf2lwwCOQYeLnP+bpW
        wyJeXKRyDY72Z0Iw85koOgkEON9axrU9dpzb10BIoto89w7Iys9eeercUQJATHzN
        U4Ov0xt6saulvo1qGF+/ZcHImFwKjor7yk4+bQK2rzgAvLDh3mGba7m0PfDzuCQI
        v77scYPAilR5TOT33QJBAMDEsZaQpABJI51f2IPZhkg+7E6TUnQZ05E8SAJfuaoC
        ufzvE5lp5v4UExX4v7hOllr/gdwzQmsxDIn8sBcMrRc=
        -----END RSA PRIVATE KEY-----

    proxy_env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
      TERM: xterm-256color
      SHELL: /bin/bash


  tasks:
      #kroki 

          #get https://dwl.netis.pl/public/servnet/servnet-1.0.10r202311160956.tgz

    - copy: content="{{ s_k2 }}" dest="/tmp/p1"

    - name: Generuje klucz miedzy kasa a centrala
      file:
       path: /tmp/p1
       mode: 0600
      no_log: true

    - name: Pobieram servnet
      get_url:
        timeout: 250
        url: https://dwl.netis.pl/public/servnet/servnet-client-1.0.10r202401301316.tgz
        dest: /opt/
      no_log: true

    - name: servnet stop
      shell: |
        systemctl stop servnet.service
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Rozpakowuje servnet'a
      unarchive:
        src: '/opt/servnet-client-1.0.10r202401301316.tgz'
        dest: '/opt/'
        remote_src: yes

    - name: Poprawiam baze serv_cli
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'serv_cli'
        query:
        - 'alter table awaitingtoken add column database_name varchar(255);'
        single_transaction: yes

    - name: Poprawiam baze serv_cli
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'serv_cli'
        query:
        - 'alter table awaitingtoken add column store_number varchar(255);'
        single_transaction: yes

    - name: Poprawiam baze serv_cli
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'serv_cli'
        query:
        - 'alter table packageregister add column databaseName varchar(255);'
        single_transaction: yes

    - name: Poprawiam baze serv_cli1
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'serv_cli'
        query:
        - 'alter table packageregister drop INDEX packageNumber;'
        single_transaction: yes

    - name: Poprawiam baze serv_cli2
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'serv_cli'
        query:
        - 'alter table packageregister add UNIQUE INDEX (packageNumber,channel,databaseName);'
        single_transaction: yes


    - name: Poprawiam baze kasa
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'kasa'
        query:
        - 'alter table Pracownicy add column idFirmy int(11) NOT NULL;'
        single_transaction: yes

    - name: Poprawiam baze kasa2
      ignore_errors: true
      community.mysql.mysql_query:
        login_db: 'kasa'
        query:
        - 'alter table OpakowaniaZbiorcze add column idJm int not null after czas;'
        single_transaction: yes

    - name: servnet start
      shell: |
        systemctl start servnet.service
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: odczytuje numer sklepu
      ignore_errors: true
      shell: |
        echo 'select stan from StanKasy where idStanu="Nrsklep";' |mysql -N kasa
      register: nrsklep

        #    - name: Zrzucam hostname kasy
        #      command: cat /etc/hostname
        #      register: local_hostname

    - name: Zrzucam hostname kasy
      shell: |
         grep ^servnet.name /etc/servnet/config.properties | cut -d '=' -f 2-2
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      register: local_hostname

    - name: config xkasnet
      blockinfile:
        owner: user
        group: user
        marker: "## {mark}"
        path: '/home/xkasnet/konfiguracja/.local'
        block: |
         app.opt.legacyEcCodeSearch=false
         app.opt.hmApiAddress=https://shop.hipercloud.pl/hmapi/api
      no_log: true

    - name: nazwa bazy hm
      shell: |
         /opt/servnet/servnet info | grep "ServnetInfo:" | grep -o "databaseName='hm*[[:digit:]]*'" | cut -d "=" -f2 | tr -d "'"
      args:
        executable: /bin/bash
      ignore_errors: yes
      register: bazaHM

    - name: tab
      shell:
            echo '\t'
      register: tab
    - name: dodanie bazy z obrazkami

      blockinfile:
        marker: "## {mark} API obrazki"
        path: '/home/kasa/konfiguracja/zmienne.dat'
        block: |
         baza_obrazkow{{ tab.stdout }}{{ bazaHM.stdout }}

    - name: wersja xasnet
      shell: mysql -N -e "select wartosc from KasyUstawienia where parametr='Klient.Wersja' order by czas desc limit 1;" kasa
      register: ver_xkasnet
      environment: "{{ proxy_env }}"

    - name: unhold paczek xkasnet'a
      shell: |
          sudo apt-mark unhold $(apt-mark showhold)
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      ignore_errors: yes

    - name:  Instalacja paczek xkasnet bionic
      apt:
        name:
          - xkasnet-client-2.2.18=2.2.18r202401120852~bionic-1
          - xkasnet-client-ec-2.2.18=2.2.18r202401120852~bionic-1
          - xkasnet-libnative-jni-2.2.18=2.2.18r202401120852~bionic-1
        state: present
        force: yes
        update_cache: yes
      when: ver_xkasnet.stdout != '2.2.18r202401120852'
      register: upgrade_xkasnet
      environment: "{{ proxy_env }}"

    - name: Zmieniam ownera na xkasnet
      file:
        path: /home/xkasnet
        state: directory
        recurse: yes
        owner: user
        group: user
      ignore_errors: yes

    - name: kasowanie danych Wlasne GrupyWlasne OPzbio KodyZw
      shell: |
         echo "delete from Wlasne" | mysql kasa
         echo "delete from GrupyWlasne" | mysql kasa
         echo "delete from OpakowaniaZbiorcze" | mysql kasa
         echo "delete from KodyZwiazane" | mysql kasa
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      ignore_errors: yes

    - name: reload
      shell: |
        ssh -i /tmp/p1 -p20320 tokenservnet@146.59.111.142 -o LogLevel=error -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "sudo servnet-server reload -c {{ local_hostname.stdout }} towaryservnet Wlasne GrupyWlasne OpakowaniaZbiorcze KodyZwiazane "
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      ignore_errors: yes
      no_log: true


    - name: czyszczenie obrazkow
      shell: |
         cp -a /home/xkasnet/katImg /home/xkasnet/katImg_backup ; cp -a /home/xkasnet/prodImg /home/xkasnet/prodImg_backup ; rm -f /home/xkasnet/katImg/* ; rm -f /home/xkasnet/prodImg/*; cp -a /home/xkasnet/prodImg_backup/log* /home/xkasnet/prodImg/ ; cd /home/xkasnet/; bash /home/xkasnet/skrypty//imgcopy.sh ; chown user.user -R /home/xkasnet/prodImg/ ; chown user.user -R /home/xkasnet/katImg/
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      ignore_errors: yes

    - name: Del key2
      file:
        state: absent
        path: '/tmp/p1'
      ignore_errors: yes
      no_log: true


